### PR TITLE
Fix CI & Linting

### LINKED ISSUE #4: Resolve CI and linting issues

### PR DESCRIPTION
**Pull request by rellfy**
Resolves #4 

`yarn lint` runs eslint
`yarn format` runs prettier on all included files
`yarn format-staged` runs pretty-quick on staged git files
`husky` is set up to run `yarn format-staged` at the pre-commit githook

### CODE REVIEW

**Review by drewflaherty — APPROVED** [review]

**Comment by xcjlo985** [comment]
@rellfy still a bunch of warnings in unchanged files. Are we going to fix these in this PR? Or another?

**Comment by rellfy** [comment]
> @rellfy still a bunch of warnings in unchanged files. Are we going to fix these in this PR? Or another?

Warnings are fixed now

**Comment by rellfy** [comment]
I've made lint warnings into errors.

**Comment by rellfy** [comment]
Husky doesn't seem to be working, I'll have a look

**Review by xcjlo985 — APPROVED** [review]

**Pull request merged**
