### PR TITLE
Replace Jest by Mocha/Chai

### LINKED ISSUE #1: Add mocha and chai
- Remove Jest
- Use mocha and chia

### PR DESCRIPTION
**Pull request by rellfy**
Resolves #1

### CODE REVIEW

**Comment by xcjlo985** [comment]
@rellfy do we want to fix the linting errors?

**Comment by rellfy** [comment]
> @rellfy do we want to fix the linting errors?

Yes, but that's a separate issue. I will create a new PR & GH issue for that

**Review by xcjlo985 — APPROVED** [review]

**Review by OptimusOpus — APPROVED** [review]
Nice work

**Review by bitcoinbrisbane — APPROVED** [review]
LGTM

**Pull request merged**
